t3n/react-packages

- packages/components/src/Slider/Slider.d.ts
- packages/components/src/Slider/Slider.tsx
- packages/storybook/src/stories/components/inputs/slider.stories.tsx
This is necessary to use the slider in more complex scenarios
> Slider should be a controlled component

- packages/components/src/PageFooter/PageFooter.tsx
> remove whatsapp from footer

- packages/components/src/Modal/Modal.d.ts
- packages/components/src/Modal/Modal.tsx
- packages/components/src/Modal/index.d.ts
- packages/components/src/Modal/index.ts
- packages/components/src/index.d.ts
- packages/components/src/index.ts
- packages/storybook/.storybook/main.js
- packages/storybook/src/stories/components/content/modal.stories.tsx
> Add Modal component

- packages/components/src/PageLayout/PageLayout.d.ts
- packages/components/src/PageLayout/PageLayout.tsx
- packages/storybook/src/stories/components/layout/pageLayout.stories.tsx
> make contactlink editable

- packages/components/src/Card/Card.d.ts
- packages/components/src/Card/Card.tsx
- packages/storybook/src/stories/components/content/card.stories.tsx
> add targetBlank property

- packages/components/src/Link/Link.d.ts
- packages/components/src/UserMenu/UserMenu.d.ts
- packages/components/src/UserMenu/UserMenu.tsx
- packages/components/src/UserMenu/index.d.ts
- packages/components/src/UserMenu/index.ts
- packages/components/src/index.d.ts
- packages/components/src/index.ts
- packages/storybook/.storybook/main.js
- packages/storybook/src/stories/components/content/userMenu.stories.tsx
- packages/storybook/src/stories/components/layout/pageHeader.stories.tsx
> Add UserMenu Component

- packages/components/src/Carousel/Carousel.d.ts
- packages/components/src/Carousel/Carousel.tsx
- packages/components/src/UserMenu/UserMenu.tsx
- packages/storybook/src/stories/components/content/carousel.stories.tsx
> Improve Styling of UserMenu and Carousel

- packages/components/src/UserMenu/UserMenu.d.ts
- packages/components/src/UserMenu/UserMenu.tsx
- packages/storybook/src/stories/components/content/userMenu.stories.tsx
- packages/storybook/src/stories/components/layout/pageHeader.stories.tsx
> Display Email instead of name in UserMenu

- packages/components/src/UserCard/UserCard.tsx
> social buttons and pioneers open blank in usercard

- packages/components/src/UserCard/UserCard.tsx
> add target blank to name link in usercard

- packages/components/src/SearchBox/SearchBox.d.ts
- packages/components/src/SearchBox/SearchBox.tsx
- packages/storybook/src/stories/components/content/searchbox.stories.tsx
> add grey variant to searchbox component

- packages/components/src/Alert/__snapshots__/Alert.test.tsx.snap
- packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/components/src/Punchline/__snapshots__/Punchline.test.tsx.snap
- packages/components/src/Switch/__snapshots__/Switch.test.tsx.snap
- packages/components/src/UserCard/UserCard.d.ts
- packages/components/src/UserCard/UserCard.tsx
- packages/storybook/src/stories/components/content/userCard.stories.tsx
> make userCard profileUrl more flexible

- packages/components/src/UserCard/UserCard.d.ts
- packages/components/src/UserCard/UserCard.tsx
- packages/storybook/src/stories/components/content/userCard.stories.tsx
> add possibility to link whole usercard again

- packages/components/src/UserCard/UserCard.tsx
> display children in userCard

- packages/components/src/ConfirmDialog/ConfirmDialog.d.ts
- packages/components/src/ConfirmDialog/ConfirmDialog.tsx
- packages/components/src/Link/Link.d.ts
- packages/storybook/src/stories/components/content/confirmDialog.stories.tsx
> add loading prop to ConfirmDialog component

- packages/components/src/ConfirmDialog/ConfirmDialog.d.ts
- packages/components/src/ConfirmDialog/ConfirmDialog.tsx
- packages/components/src/Modal/Modal.d.ts
- packages/components/src/Modal/Modal.tsx
- packages/storybook/src/stories/components/content/confirmDialog.stories.tsx
- packages/storybook/src/stories/components/content/modal.stories.tsx
> add wide and width prop to modal and confirmdialog

- packages/components/src/AuthorCard/__snapshots__/AuthorCard.test.tsx.snap
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
- packages/components/src/Card/__snapshots__/Card.test.tsx.snap
- packages/components/src/IconButton/IconButton.d.ts
- packages/components/src/IconButton/IconButton.tsx
- packages/components/src/IconButton/index.d.ts
- packages/components/src/IconButton/index.ts
- packages/components/src/Link/Link.d.ts
- packages/components/src/Loader/Loader.d.ts
- packages/components/src/Loader/Loader.tsx
- packages/components/src/index.d.ts
- packages/components/src/index.ts
- packages/storybook/.storybook/main.js
- packages/storybook/src/stories/components/content/iconButton.stories.tsx
- packages/storybook/src/stories/components/inputs/iconButton.stories.tsx
> Add IconButton component

- packages/components/src/Tag/Tag.d.ts
- packages/components/src/Tag/Tag.tsx
- packages/storybook/src/stories/components/content/tag.stories.tsx
> Add colorVariant highlight to Tag component

- packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
- packages/components/src/LegacyHeader/LegacyHeader.d.ts
- packages/components/src/LegacyHeader/LegacyHeader.tsx
- packages/components/src/LegacyPageLayout/LegacyPageLayout.d.ts
- packages/components/src/LegacyPageLayout/LegacyPageLayout.tsx
- packages/components/src/LegacyPageLayout/index.d.ts
- packages/components/src/LegacyPageLayout/index.ts
- packages/components/src/index.d.ts
- packages/components/src/index.ts
- packages/storybook/.storybook/main.js
- packages/storybook/src/stories/legacy/content/legacyAd.stories.tsx
- packages/storybook/src/stories/legacy/layout/legacyPageLayout.stories.tsx
> Add LegacyPageLayout component

- packages/components/src/LegacyAd/LegacyAd.tsx
- packages/components/src/LegacyHeader/LegacyDesktopHeader.d.ts
- packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
- packages/components/src/LegacyHeader/LegacyHeader.d.ts
- packages/components/src/LegacyHeader/LegacyHeader.tsx
- packages/components/src/LegacyHeader/LegacyMobileHeader.d.ts
- packages/components/src/LegacyPageLayout/LegacyPageLayout.d.ts
- packages/components/src/LegacyPageLayout/LegacyPageLayout.tsx
- packages/storybook/src/stories/legacy/layout/legacyPageLayout.stories.tsx
> add p0, p1, p2, p13 legacyAds to legacyPageLayout

- packages/components/src/Ad/Ad.tsx
- packages/components/src/LegacyAd/LegacyAd.d.ts
- packages/components/src/LegacyAd/LegacyAd.tsx
- packages/components/src/LegacyPageLayout/LegacyPageLayout.tsx
- packages/storybook/src/stories/legacy/content/legacyAd.stories.tsx
> Update legacy ad component

- packages/components/src/LegacyAd/LegacyAd.tsx
- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
- packages/components/src/LegacyHeader/components/LegacyMainNav.tsx
- packages/components/src/LegacyHeader/components/LegacyTagNav.tsx
> Improve legacy layout

- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
wollte ich nur erledigt haben, pushe ich jetzt nicht direkt als patch
> fix mobile legacy layout news indicator

- Dockerfile
This reverts commit f7b73e7b51545dfc5ae92c044c555513e5511f4b.
* ...
(if necessary)
Resolves TECHNIK-
> Revert "Fix permissions on npm logs"

- packages/components/src/PageHeader/PageHeader.d.ts
- packages/components/src/PageHeader/PageHeader.tsx
- packages/components/src/PageLayout/PageLayout.d.ts
- packages/components/src/PageLayout/PageLayout.tsx
- packages/components/src/UserMenu/UserMenu.d.ts
- packages/components/src/UserMenu/UserMenu.tsx
- packages/storybook/src/stories/components/layout/pageHeader.stories.tsx
- packages/storybook/src/stories/components/layout/pageLayout.stories.tsx
* see pr title
(if necessary)
Resolves TECHNIK-11481
> add light variant to header and usermenu

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
* added link
Resolves TECHNIK-11468
> Vertriebskampagne22

- packages/components/src/LegacyHeader/components/LegacyT3nNav.tsx
* ...
(if necessary)
Resolves TECHNIK-
> found wrong url..whops

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
> add footer link

- packages/components/src/Avatar/Avatar.d.ts
- packages/components/src/Avatar/Avatar.tsx
- packages/components/src/UserCard/UserCard.d.ts
- packages/components/src/UserCard/UserCard.tsx
- packages/storybook/src/stories/components/content/avatar.stories.tsx
- packages/storybook/src/stories/components/content/userCard.stories.tsx
* Avatar has a new prop to allow an non optimized image src
* UserCard respects new Avatar prop
> Avatar and UserCard can be used with custom img src

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
- packages/components/src/PageFooter/PageFooter.tsx
> Added recovation policy

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
* Use https in footer outlinks
* Remove trailing slash from footer outlinks
Resolves GREEN-183
> Change footer outlinks

- packages/components/src/PageFooter/PageFooter.tsx
* Fixed styling of footer
Resolves GREEN-177
> Fixed styling of footer

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
> Changed mission

- packages/components/src/Image/Image.tsx
- packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
- packages/storybook/src/stories/components/content/image.stories.tsx
- packages/storybook/src/stories/legacy/content/legacyNewsCard.stories.tsx
* Srcset generation should override existing class param
* LegacyNews Card should use the FastlyImage Component
* Adapt stories
(if necessary)
> Legacy News Card should use Fastly Image Component

- packages/components/src/SelectBox/SelectBox.d.ts
* add missing update for selectbox type
> update types selectbox

- packages/components/src/DatePicker/DatePicker.tsx
- packages/storybook/src/stories/components/inputs/datePicker.stories.tsx
> add reset button to datepicker

- packages/components/src/Ad/Ad.tsx
> Always center content in ad component

- packages/components/src/Accordion/Accordion.test.tsx
- packages/components/src/Accordion/Accordion.tsx
- packages/components/src/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/storybook/src/stories/components/content/accordion.stories.tsx
> add possibility to add jsx.element instead of string as accordion title

- packages/components/src/Accordion/Accordion.d.ts
- packages/components/src/helper/renderWithTheme.d.ts
> forgot to run build

- packages/components/src/LegacyHeader/components/LegacyMainNav.tsx
- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
> add online-kurse to menu

- packages/components/src/Alert/__snapshots__/Alert.test.tsx.snap
- packages/components/src/Badge/Badge.d.ts
- packages/components/src/Badge/Badge.tsx
- packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/components/src/Switch/__snapshots__/Switch.test.tsx.snap
- packages/storybook/src/stories/components/content/badge.stories.tsx
- packages/theme/src/theme/colors/colors.d.ts
- packages/theme/src/theme/colors/colors.ts
> exchange green and add green to badge variants

- package-lock.json
- packages/components/src/Button/Button.tsx
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
- packages/components/src/IconButton/IconButton.tsx
- packages/components/src/SocialButton/SocialButton.tsx
- packages/storybook/package.json
> fix problems

- package-lock.json
- packages/components/src/DatePicker/DatePicker.d.ts
- packages/components/src/DatePicker/DatePicker.tsx
- packages/components/src/DatePicker/DateRangePickerGlobalStyles.tsx
> Added isOutsideRange for DateRangePicker

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
- packages/components/src/PageFooter/PageFooter.tsx
- packages/components/src/PageLayout/PageLayout.tsx
- packages/storybook/src/stories/components/layout/pageFooter.stories.tsx
- packages/storybook/src/stories/components/layout/pageLayout.stories.tsx
- packages/storybook/src/stories/storybook/introduction.story.mdx
> add abo cancellation and restructure footer

- packages/components/src/LegacyHeader/LegacyMobileHeader.tsx
> increase z-index to fix dspx-p4 problem

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
- packages/components/src/LegacyHeader/components/LegacyMainNav.tsx
- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
* ...
Resolves [682](https://yeebase.atlassian.net/browse/GREEN-682)
> remove trailing slash from pro-artikel

- packages/components/src/Alert/Alert.tsx
- packages/components/src/Alert/__snapshots__/Alert.test.tsx.snap
- packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/theme/src/theme/colors/colors.d.ts
- packages/theme/src/theme/colors/colors.ts
Resolves [PURPLE-417](https://yeebase.atlassian.net/browse/PURPLE-417)
[PURPLE-417]: https://yeebase.atlassian.net/browse/PURPLE-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add border and change color

- packages/components/src/LegacyBreadcrumb/LegacyBreadcrumb.tsx
- packages/components/src/LegacyPageLayout/LegacyPageLayout.tsx
- packages/components/src/LegacySection/LegacySection.d.ts
- packages/components/src/LegacySection/LegacySection.tsx
- packages/components/src/LegacySection/index.d.ts
- packages/components/src/LegacySection/index.ts
- packages/components/src/index.d.ts
- packages/components/src/index.ts
- packages/storybook/.storybook/main.js
- packages/storybook/src/stories/legacy/layout/legacyPageLayout.stories.tsx
- packages/storybook/src/stories/legacy/layout/legacySection.stories.tsx
> add LegacySection and improve some Legacy components

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyHeader/components/LegacyMainNav.tsx
- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
> feat: :sparkles: remove pioneers from nav and move magazin in nav

- packages/components/package.json
- packages/storybook/package.json
* ...
(if necessary)
Resolves TECHNIK-
> fix: reset version

- packages/components/src/Ad/Ad.tsx
> fix: :bug: adjust adlabel styling

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/PageFooter/PageFooter.tsx
* replace mission statement h3 tag with p
Resolves [GREEN-972](https://yeebase.atlassian.net/browse/GREEN-972)
[GREEN-972]: https://yeebase.atlassian.net/browse/GREEN-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> replace footer h3

- packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
* change markup in LegacyNewsCard from h4 to h3
Resolves [GREEN-830](https://yeebase.atlassian.net/browse/GREEN-830)
[GREEN-830]: https://yeebase.atlassian.net/browse/GREEN-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: optimize headings for seo

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
* set smaller font-size for every element in footer
before: year strings has wrong font-size
Resolves [GREEN-972](https://yeebase.atlassian.net/browse/GREEN-972)
[GREEN-972]: https://yeebase.atlassian.net/browse/GREEN-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: smaller font-size in footer

- packages/components/src/Ad/Ad.tsx
* ...
(if necessary)
Resolves [GREEN-1082](https://yeebase.atlassian.net/browse/GREEN-1082)
[GREEN-1082]: https://yeebase.atlassian.net/browse/GREEN-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add 100% width to top adzone

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyFooter/LegacyMobileFooter.d.ts
- packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
- packages/components/src/PageFooter/PageFooter.tsx
- packages/storybook/src/stories/components/layout/pageFooter.stories.tsx
> feat: :sparkles: add faq and contact to footers

- packages/components/src/Ad/Ad.tsx
> feat: add dspx_scroller container to adunits

- packages/components/src/Ad/Ad.tsx
* switch width property to parent container
Resolves [GREEN-1137](https://yeebase.atlassian.net/browse/GREEN-1137)
[GREEN-1137]: https://yeebase.atlassian.net/browse/GREEN-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update T3N_D_Top CSS properties

- packages/components/src/Ad/Ad.tsx
* add full width property to child of ad wrapper
Resolves [GREEN-1137](https://yeebase.atlassian.net/browse/GREEN-1137)
[GREEN-1137]: https://yeebase.atlassian.net/browse/GREEN-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update ad wrapper styling

- packages/components/src/Ad/Ad.tsx
Changes
* only center ad if its not right zone
> update ad wrapper style

- packages/components/src/Ad/Ad.tsx
> fix: :bug: remove T3N_D_Incontent-2 as possibility for dspx_scroller

- packages/components/src/Ad/Ad.tsx
> fix: :bug: fix bad styling

- packages/components/src/Image/Image.tsx
> fix: :bug: use correct src for placeholder in image component

- packages/components/src/Ad/Ad.tsx
> fix: :bug: add missing styling for bAd

- packages/components/src/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
- packages/components/src/NProgressBarGlobalStyle/NProgressBarGlobalStyle.d.ts
- packages/theme/src/theme/colors/colors.d.ts
- packages/theme/src/theme/colors/colors.ts
Resolves [TECH-453](https://yeebase.atlassian.net/browse/TECH-453)
[TECH-453]: https://yeebase.atlassian.net/browse/TECH-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: include and apply #5F5F5F as grey95

- packages/components/src/Accordion/Accordion.tsx
- packages/components/src/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/components/src/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/DatePicker/DateRangePickerGlobalStyles.tsx
- packages/components/src/DatePicker/SingleDatePickerGlobalStyles.tsx
- packages/components/src/Input/Input.tsx
- packages/components/src/JobCard/JobCard.tsx
- packages/components/src/LegacyArticleSocialShare/LegacyArticleSocialShare.tsx
- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
- packages/components/src/LegacyHeader/components/LegacyTagNav.tsx
- packages/components/src/LegacyNewsCard/LegacyBookmark.tsx
- packages/components/src/LegacySocialBar/LegacySocialBar.tsx
- packages/components/src/NProgressBarGlobalStyle/NProgressBarGlobalStyle.d.ts
- packages/components/src/PageFooter/PageFooter.tsx
- packages/components/src/RadioButton/RadioButton.tsx
- packages/components/src/SelectBox/SelectBox.tsx
- packages/components/src/Switch/Switch.tsx
- packages/components/src/Switch/__snapshots__/Switch.test.tsx.snap
- packages/components/src/Textarea/Textarea.tsx
- packages/theme/src/theme/colors/colors.d.ts
- packages/theme/src/theme/colors/colors.ts
- packages/theme/src/theme/linkStyles.ts
Resolves [TECH-453](https://yeebase.atlassian.net/browse/TECH-453)
[TECH-453]: https://yeebase.atlassian.net/browse/TECH-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: completely replace grey143 with grey95

- packages/components/src/LegacyBigRoundButton/LegacyBigRoundButton.tsx
> feat: :art: use more terse color for editorial staff socials too

- packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> fix: :bug: bring back mobile version of legacyNewsCard

- packages/components/src/Ad/Ad.tsx
- packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
- packages/components/src/LegacyNewsCard/LegacyNewsCardHeadline.tsx
- packages/storybook/src/stories/components/content/ad.stories.tsx
- packages/storybook/src/stories/legacy/content/legacyAd.stories.tsx
- packages/storybook/src/stories/legacy/content/legacyBigRoundButton.stories.tsx
> feat: :sparkles: adjust mobile incontent-ads to be sticky

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyHeader/components/LegacyMainNav.tsx
- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
> feat: :sparkles: remove /firmen/ from legacy nav & footer

- .github/git-pr-sanity.yaml
- .github/git-pr-size.yaml
> ci: add pr sanity & size

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
- packages/components/src/LegacyHeader/LegacyDesktopHeader.d.ts
- packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
- packages/components/src/LegacyHeader/LegacyHeader.d.ts
- packages/components/src/LegacyHeader/LegacyHeader.tsx
- packages/components/src/LegacyHeader/LegacyMobileHeader.d.ts
- packages/components/src/LegacyHeader/LegacyMobileHeader.tsx
- packages/components/src/LegacyHeader/components/LegacyMainNav.tsx
- packages/components/src/LegacyHeader/components/LegacyMobileNav.d.ts
- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
- packages/components/src/LegacyHeader/components/LegacyT3nNav.d.ts
- packages/components/src/LegacyHeader/components/LegacyT3nNav.tsx
- packages/components/src/LegacyNewsCard/LegacyNewsCard.d.ts
- packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
- packages/components/src/LegacyNewsCard/LegacyNewsCardHeadline.d.ts
- packages/components/src/LegacyNewsCard/LegacyNewsCardHeadline.tsx
- packages/components/src/LegacyPageLayout/LegacyPageLayout.d.ts
- packages/components/src/LegacyPageLayout/LegacyPageLayout.tsx
- packages/components/src/UserMenu/UserMenu.d.ts
- packages/components/src/UserMenu/UserMenu.tsx
- packages/icons/src/svg/t3n/plus.svg
- packages/storybook/src/stories/components/content/userMenu.stories.tsx
- packages/storybook/src/stories/components/layout/pageHeader.stories.tsx
- packages/storybook/src/stories/components/layout/pageLayout.stories.tsx
- packages/storybook/src/stories/legacy/content/legacyNewsCard.stories.tsx
- packages/storybook/src/stories/legacy/layout/legacyHeader.stories.tsx
- packages/storybook/src/stories/legacy/layout/legacyPageLayout.stories.tsx
#TECH-1340 #TECH-1525 #TECH-1526
> feat: :sparkles: exchange pro with plus

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
- packages/components/src/LegacyHeader/LegacyDesktopHeader.d.ts
- packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
- packages/components/src/LegacyHeader/LegacyHeader.d.ts
- packages/components/src/LegacyHeader/LegacyHeader.tsx
- packages/components/src/LegacyHeader/LegacyMobileHeader.d.ts
- packages/components/src/LegacyHeader/LegacyMobileHeader.tsx
- packages/components/src/LegacyHeader/components/LegacyMainNav.tsx
- packages/components/src/LegacyHeader/components/LegacyMobileNav.d.ts
- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
- packages/components/src/LegacyHeader/components/LegacyT3nNav.d.ts
- packages/components/src/LegacyHeader/components/LegacyT3nNav.tsx
- packages/components/src/LegacyNewsCard/LegacyNewsCard.d.ts
- packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
- packages/components/src/LegacyNewsCard/LegacyNewsCardHeadline.d.ts
- packages/components/src/LegacyNewsCard/LegacyNewsCardHeadline.tsx
- packages/components/src/LegacyPageLayout/LegacyPageLayout.d.ts
- packages/components/src/LegacyPageLayout/LegacyPageLayout.tsx
- packages/components/src/UserMenu/UserMenu.d.ts
- packages/components/src/UserMenu/UserMenu.tsx
- packages/icons/src/svg/t3n/plus.svg
- packages/storybook/src/stories/components/content/userMenu.stories.tsx
- packages/storybook/src/stories/components/layout/pageHeader.stories.tsx
- packages/storybook/src/stories/components/layout/pageLayout.stories.tsx
- packages/storybook/src/stories/legacy/content/legacyNewsCard.stories.tsx
- packages/storybook/src/stories/legacy/layout/legacyHeader.stories.tsx
- packages/storybook/src/stories/legacy/layout/legacyPageLayout.stories.tsx
This reverts commit 70313ac815520ccf4557d2cf4f6fcf1f3e82633e, reversing changes made to 8b376a2a6be402439596f4459ab51a11f7cc0183.
ich reverte, damit nicht versehentlich was ausgespielt wird. 
gemerged habe ich, damit ich im feature-paywall die paywall version benutzen kann
> Revert "Merge pull request #1001 from t3n/plus-badge"

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
- packages/components/src/LegacyHeader/LegacyDesktopHeader.d.ts
- packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
- packages/components/src/LegacyHeader/LegacyHeader.d.ts
- packages/components/src/LegacyHeader/LegacyHeader.tsx
- packages/components/src/LegacyHeader/LegacyMobileHeader.d.ts
- packages/components/src/LegacyHeader/LegacyMobileHeader.tsx
- packages/components/src/LegacyHeader/components/LegacyMainNav.tsx
- packages/components/src/LegacyHeader/components/LegacyMobileNav.d.ts
- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
- packages/components/src/LegacyHeader/components/LegacyT3nNav.d.ts
- packages/components/src/LegacyHeader/components/LegacyT3nNav.tsx
- packages/components/src/LegacyNewsCard/LegacyNewsCard.d.ts
- packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
- packages/components/src/LegacyNewsCard/LegacyNewsCardHeadline.d.ts
- packages/components/src/LegacyNewsCard/LegacyNewsCardHeadline.tsx
- packages/components/src/LegacyPageLayout/LegacyPageLayout.d.ts
- packages/components/src/LegacyPageLayout/LegacyPageLayout.tsx
- packages/components/src/UserMenu/UserMenu.d.ts
- packages/components/src/UserMenu/UserMenu.tsx
- packages/icons/src/svg/t3n/plus.svg
- packages/storybook/src/stories/components/content/userMenu.stories.tsx
- packages/storybook/src/stories/components/layout/pageHeader.stories.tsx
- packages/storybook/src/stories/components/layout/pageLayout.stories.tsx
- packages/storybook/src/stories/legacy/content/legacyNewsCard.stories.tsx
- packages/storybook/src/stories/legacy/layout/legacyHeader.stories.tsx
- packages/storybook/src/stories/legacy/layout/legacyPageLayout.stories.tsx
This reverts commit 9ad8d7e165019c06697f34886d39daecf3fd43ce, reversing changes made to db139e9ae1cb3db6614fc52f9fe37084fa3dc03c.
> Revert "Merge pull request #1002 from t3n/revert-feature-paywall"

- packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
- packages/components/src/LegacyHeader/components/LegacyT3nNav.tsx
> feat: :sparkles: remove social icons in header in favor of /abos button

- packages/components/src/IconButton/IconButton.d.ts
- packages/components/src/IconButton/IconButton.tsx
- packages/components/src/LegacyFooter/LegacyDesktopFooter.d.ts
- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyFooter/LegacyFooter.d.ts
- packages/components/src/LegacyFooter/LegacyFooter.tsx
- packages/components/src/LegacyFooter/LegacyMobileFooter.d.ts
- packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
- packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
- packages/components/src/LegacyHeader/components/LegacyMainNav.d.ts
- packages/components/src/LegacyHeader/components/LegacyMainNav.tsx
- packages/components/src/LegacyHeader/components/LegacyMobileNav.tsx
- packages/components/src/LegacyPageLayout/LegacyPageLayout.tsx
> feat: :sparkles: set /dein-abo label dynamically

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
> chore: exchange url in legacy footer

- packages/components/src/UserMenu/UserMenu.d.ts
- packages/components/src/UserMenu/UserMenu.tsx
> feat: :sparkles: adjust user-menu to fit new ssb

- packages/components/src/Carousel/Carousel.d.ts
- packages/components/src/Carousel/Carousel.tsx
- packages/storybook/src/stories/components/content/carousel.stories.d.ts
- packages/storybook/src/stories/components/content/carousel.stories.tsx
part of [TECH-1997](https://yeebase.atlassian.net/browse/TECH-1997)
[TECH-1997]: https://yeebase.atlassian.net/browse/TECH-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: allow chevron icon as button for carousel

- packages/components/src/Modal/Modal.tsx
- Abgesprochen mit Lea
- Teil von [TECH-1997](https://yeebase.atlassian.net/browse/TECH-1997)
[TECH-1997]: https://yeebase.atlassian.net/browse/TECH-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: remove bubble around X-button

- packages/components/src/Carousel/Carousel.d.ts
- packages/components/src/Carousel/Carousel.tsx
- packages/components/src/Modal/Modal.d.ts
- packages/components/src/Modal/Modal.tsx
- adjustments to meet design requirements of [TECH-1997](https://yeebase.atlassian.net/browse/TECH-1997)
[TECH-1997]: https://yeebase.atlassian.net/browse/TECH-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: make adjustments to modal and carousel (slick-slider)

- packages/components/src/Carousel/Carousel.tsx
- packages/components/src/Modal/Modal.tsx
- resolve feedback in [TECH-1997](https://yeebase.atlassian.net/browse/TECH-1997)
[TECH-1997]: https://yeebase.atlassian.net/browse/TECH-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: adjust styles for very small screens

- packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
- packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
- packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
> feat: :sparkles: adjust navi button leading to abos page

- packages/storybook/src/stories/components/inputs/button.stories.tsx
> chore: add missing button stories

- packages/components/src/UserCard/UserCard.tsx
> chore: :bug: adjust usercard component to fix hydration errors #2

- packages/components/src/ArticleTeaser/ArticleTeaser.tsx
> fix: :bug: adjust small teaser image optimization and grid for article teaser

- packages/components/src/Content/Content.tsx
- packages/components/src/LegacyFooter/LegacyFooter.tsx
- packages/components/src/LegacySection/LegacySection.tsx
> feat: :sparkles: adjust width of content and footer to match new header

- packages/components/src/PageHeader/components/TagBar.tsx
- packages/storybook/src/stories/components/layout/pageFooter.stories.tsx
> fix: :bug: fix margin of plus badge in pinnedTeaser

- packages/components/src/ArticleTeaser/ArticleTeaser.tsx
[TECH-2502](https://yeebase.atlassian.net/browse/TECH-2502)
- article teaser images also need alt texts
[TECH-2502]: https://yeebase.atlassian.net/browse/TECH-2502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(a11y): alt texts for article teaser images

- packages/components/src/PageFooter/DesktopFooter.tsx
- packages/components/src/PageFooter/MobileFooter.tsx
[TECH-2495](https://yeebase.atlassian.net/browse/TECH-2495)
[TECH-2495]: https://yeebase.atlassian.net/browse/TECH-2495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: link to bfsg legal text in footer

- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/components/src/PageHeader/components/BurgerAccordion.d.ts
- packages/components/src/PageHeader/components/BurgerAccordion.tsx
- packages/components/src/PageHeader/components/BurgerNav.tsx
- packages/components/src/PageHeader/components/TagBar.tsx
- packages/components/src/SearchBox/SearchBoxWrapper.d.ts
- packages/components/src/SearchBox/SearchBoxWrapper.tsx
> fix: :bug: fix tabbing in navigation

- .github/pull_request_template.md
- .gitignore
* update template
* add .idea to .gitignore
> chore: update template

- packages/components/src/LegacyArticleSocialShare/LegacyArticleSocialShare.d.ts
- packages/components/src/LegacyBookmarkModal/LegacyBookmarkModal.d.ts
- packages/components/src/SocialButton/SocialButton.d.ts
- packages/theme/src/theme/colors/colors.d.ts
> chore: push missing files
